#*************************************************************************
#
# Copyright 2011-2013 Ibrahim Sha'ath
#
# This file is part of KeyFinder.
#
# KeyFinder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KeyFinder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KeyFinder.  If not, see <http://www.gnu.org/licenses/>.
#
#*************************************************************************

# CURRENT DEPENDENCIES:
# qt               5.4.1
# libkeyfinder     2.2.1
#  \-> fftw        3.3.4
# libav            0.7.7
# taglib           1.10

######################################################################
# Automatically generated by qmake (3.1) Mon Aug 17 14:33:41 2020
######################################################################

TEMPLATE = app
TARGET = is_KeyFinder
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

<<<<<<< HEAD
include(./source/source.pri)
include(./forms/forms.pri)

CONFIG(test) {
  TARGET = KeyFinderTests
  include(./test/test.pri)
  SOURCES += $$PWD/test/main.cpp
  CONFIG += console
  CONFIG -= app_bundle
  LIBS += -lgtest
} else {
  TARGET = KeyFinder
  SOURCES += $$PWD/source/main.cpp
  include(./resources/resources.pri)
  UI_DIR = ui
}

OTHER_FILES += README

QMAKE_CXXFLAGS += -D__STDC_CONSTANT_MACROS # for libav

unix|macx {
  LIBS += -L/usr/local/lib
  LIBS += -lkeyfinder
  LIBS += -lavcodec
  LIBS += -lavformat
  LIBS += -lavutil
  LIBS += -ltag
  LIBS += -lz
}

macx {
  DEPENDPATH += /usr/local/lib
  INCLUDEPATH += /usr/local/include

  QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7
  QMAKE_MAC_SDK = macosx10.13
  CONFIG -= ppc ppc64 x86
  CONFIG += x86_64
}

win32 {
  QT += xml xmlpatterns
  INCLUDEPATH += C:/mingw32/local/include
  DEPENDPATH += C:/mingw32/local/bin
  LIBS += -LC:/mingw32/local/bin
  LIBS += -lkeyfinder0
  LIBS += -lavcodec
  LIBS += -lavformat
  LIBS += -lavutil
  LIBS += -llibtag
  LIBS += -LC:/mingw32/local/lib
}

unix {
  QT += xml xmlpatterns
  INCLUDEPATH += /usr/include/c++/10.1.0
  INCLUDEPATH += /usr/include/c++/10.1.0/x86_64-pc-linux-gnu
  target.path = $$[QT_INSTALL_PREFIX]/bin
  INSTALLS += target
}

######################################################################
# Automatically generated by qmake (3.1) Mon Aug 17 14:33:41 2020
######################################################################

TARGET = is_KeyFinder
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

=======
>>>>>>> construction_zone
# Input
HEADERS += source/_VERSION.h \
           source/asyncfileobject.h \
           source/asynckeyprocess.h \
           source/asynckeyresult.h \
           source/asyncmetadatareadprocess.h \
           source/asyncmetadatareadresult.h \
           source/avfilemetadata.h \
           source/avfilemetadatafactory.h \
           source/decoderlibav.h \
           source/externalplaylistprovider.h \
           source/externalplaylistproviderserato.h \
           source/guiabout.h \
           source/guibatch.h \
           source/guimenuhandler.h \
           source/guiprefs.h \
           source/metadatafilename.h \
           source/metadatawriteresult.h \
           source/os_windows.h \
           source/preferences.h \
           source/settingswrapper.h \
           source/strings.h \
           test/asyncfileobjecttest.h \
           test/avfilemetadatatest.h \
           test/decoderlibavtest.h \
           test/preferencestest.h
FORMS += forms/aboutdialog.ui forms/batchwindow.ui forms/prefsdialog.ui
SOURCES += source/asynckeyprocess.cpp \
           source/asyncmetadatareadprocess.cpp \
           source/avfilemetadata.cpp \
           source/avfilemetadatafactory.cpp \
           source/decoderlibav.cpp \
           source/externalplaylistprovider.cpp \
           source/externalplaylistproviderserato.cpp \
           source/guiabout.cpp \
           source/guibatch.cpp \
           source/guimenuhandler.cpp \
           source/guiprefs.cpp \
           source/main.cpp \
           source/metadatafilename.cpp \
           source/os_windows.cpp \
           source/preferences.cpp \
           source/settingswrapper.cpp \
           source/strings.cpp \
           test/asyncfileobjecttest.cpp \
           test/avfilemetadatatest.cpp \
           test/decoderlibavtest.cpp \
           test/main.cpp \
           test/preferencestest.cpp
RESOURCES += resources/resources.qrc
TRANSLATIONS += translations/is_keyfinder_en_GB.ts
